# Generated by Django 3.2.4 on 2021-08-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='posts_categories',
        ),
    ]
